sudo: required
language: csharp
services:
  - docker
solution: Glossiator.sln
after_success:
  - docker build -t dustinmoris/glossiator ./Glossiator/bin/Release
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push dustinmoris/glossiator